[package]
name = "boreas"
version = "0.2.0"
edition = "2024"
description = "Parallel git repo puller with live progress, dirty detection, and safe defaults"
license = "MIT"
repository = "https://github.com/EmreCelenli/boreas"
keywords = ["git", "cli", "pull", "async", "productivity"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
tokio = { version = "1.44.0", features = ["rt-multi-thread", "process", "macros", "sync"] }
clap = { version = "4.5.35", features = ["derive"] }
indicatif = "0.17.11"
colored = "3.0.0"
walkdir = "2.5.0"
anyhow = "1.0.97"
num_cpus = "1.16.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
